import type { Metadata } from "next";
import "./globals.css";
import { LucideHouse, LucideReceiptText, LucideSearch, LucideUser } from "lucide-react";
import Link from "next/link";
import { CldOgImage } from "next-cloudinary";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <script 
        src="https://upload-widget.cloudinary.com/global/all.js" 
        async 
        defer
      />

      <body
        className={`antialiased p-4`}
      >
        <AuthProvider>
        {children}
        <CldOgImage src="og-image" alt="social image"/>



        <nav className="bg-black/30 backdrop-blur-md border border-white/10 shadow-lg rounded-md p-2 fixed bottom-0 left-0 w-full flex items-center justify-around">
          <Link href="/" className="rounded-md p-2 hover:bg-zinc-600 cursor-pointer">
            <LucideHouse />
          </Link>
          <Link href="/" className="rounded-md p-2 hover:bg-zinc-600 cursor-pointer">
            <LucideSearch />
          </Link>
          <Link href="/" className="rounded-md p-2 hover:bg-zinc-600 cursor-pointer">
            <LucideReceiptText />
          </Link>
          <Link href="/user" className="rounded-md p-2 hover:bg-zinc-600 cursor-pointer">
            <LucideUser />
          </Link>
          </nav>
          </AuthProvider>
      </body>

    </html>
    
  );
}
